# Generated by Django 4.2.16 on 2026-04-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_driverlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='שם רואה החשבון', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary accountant (used for sending reports)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accountant',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('driver', 'Driver'), ('accountant', 'Accountant')], max_length=15)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body_preview', models.TextField(blank=True)),
                ('attachment_name', models.CharField(blank=True, max_length=300)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payroll')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='core_payrol_sent_at_2a4658_idx'), models.Index(fields=['recipient_type', '-sent_at'], name='core_payrol_recipie_c2b13c_idx')],
            },
        ),
    ]
