# Generated by Django 4.2.16 on 2026-04-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accountant_payrollsendlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_1_limit', models.DecimalField(decimal_places=2, default=7010, help_text='Bracket 1 upper limit (monthly)', max_digits=10)),
                ('bracket_1_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('bracket_2_limit', models.DecimalField(decimal_places=2, default=10060, max_digits=10)),
                ('bracket_2_rate', models.DecimalField(decimal_places=4, default=0.14, max_digits=5)),
                ('bracket_3_limit', models.DecimalField(decimal_places=2, default=19000, max_digits=10)),
                ('bracket_3_rate', models.DecimalField(decimal_places=4, default=0.2, max_digits=5)),
                ('bracket_4_limit', models.DecimalField(decimal_places=2, default=25100, max_digits=10)),
                ('bracket_4_rate', models.DecimalField(decimal_places=4, default=0.31, max_digits=5)),
                ('bracket_5_limit', models.DecimalField(decimal_places=2, default=46690, max_digits=10)),
                ('bracket_5_rate', models.DecimalField(decimal_places=4, default=0.35, max_digits=5)),
                ('bracket_6_limit', models.DecimalField(decimal_places=2, default=60130, max_digits=10)),
                ('bracket_6_rate', models.DecimalField(decimal_places=4, default=0.47, max_digits=5)),
                ('bracket_7_rate', models.DecimalField(decimal_places=4, default=0.5, help_text='Above bracket 6 — top rate', max_digits=5)),
                ('insurance_low_limit', models.DecimalField(decimal_places=2, default=7703, max_digits=10)),
                ('insurance_high_limit', models.DecimalField(decimal_places=2, default=51910, max_digits=10)),
                ('national_insurance_low', models.DecimalField(decimal_places=4, default=0.0104, max_digits=6)),
                ('national_insurance_high', models.DecimalField(decimal_places=4, default=0.07, max_digits=6)),
                ('health_insurance_low', models.DecimalField(decimal_places=4, default=0.0323, max_digits=6)),
                ('health_insurance_high', models.DecimalField(decimal_places=4, default=0.0517, max_digits=6)),
                ('tax_point_value', models.DecimalField(decimal_places=2, default=242, help_text='Monthly ILS value per tax point (2026)', max_digits=8)),
                ('base_tax_points', models.DecimalField(decimal_places=2, default=2.25, help_text='Default points for Israeli resident', max_digits=4)),
                ('minimum_wage_monthly', models.DecimalField(decimal_places=2, default=5880.02, max_digits=10)),
                ('minimum_wage_hourly', models.DecimalField(decimal_places=2, default=32.3, max_digits=6)),
                ('overtime_125_limit', models.DecimalField(decimal_places=1, default=2, help_text='First N OT hours at 125%', max_digits=4)),
                ('overtime_125_rate', models.DecimalField(decimal_places=2, default=1.25, max_digits=4)),
                ('overtime_150_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('effective_year', models.IntegerField(default=2026)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Payroll Configuration',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='extra_tax_points',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional manual tax points', max_digits=4),
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('male', 'זכר'), ('female', 'נקבה')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='immigrant_since',
            field=models.DateField(blank=True, help_text='תאריך עלייה', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_immigrant',
            field=models.BooleanField(default=False, help_text='עולה חדש'),
        ),
        migrations.CreateModel(
            name='ChildOfDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField()),
                ('has_disability', models.BooleanField(default=False, help_text='ילד בעל מוגבלות')),
                ('receives_allowance', models.BooleanField(default=False, help_text='מקבל קצבה מהורה גרוש (מפחית נקודת זיכוי)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.driver')),
            ],
            options={
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'טיוטה'), ('approved', 'מאושר'), ('paid', 'שולם')], default='draft', max_length=10)),
                ('working_days', models.IntegerField(default=0)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overtime_125_h', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overtime_150_h', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('crane_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('base_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_125_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_150_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('crane_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_points_used', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('national_ins', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health_ins', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pension_emp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('study_fund_emp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pension_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('study_fund_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('severance_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='core.driver')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['-year', '-month'], name='core_paysli_year_ba4304_idx'), models.Index(fields=['driver', '-year', '-month'], name='core_paysli_driver__2cf4f8_idx')],
                'unique_together': {('driver', 'year', 'month')},
            },
        ),
    ]
