# Generated by Django 4.2.16 on 2026-04-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payrollconfig_driver_extra_tax_points_driver_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_125_h',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hours at 125% (first 2 OT hours)', max_digits=6),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_150_h',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hours at 150% (beyond 10h/day)', max_digits=6),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hours at normal rate', max_digits=6),
        ),
    ]
