# Generated by Django 4.2.16 on 2026-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attendance_overtime_125_h_attendance_overtime_150_h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='has_pension',
            field=models.BooleanField(default=False, help_text='זכאי לפנסיה — אם False, אין ניכוי גם אם האחוז מוגדר'),
        ),
        migrations.AddField(
            model_name='driver',
            name='has_study_fund',
            field=models.BooleanField(default=False, help_text='זכאי לקרן השתלמות — אם False, אין ניכוי גם אם האחוז מוגדר'),
        ),
    ]
