# Generated by Django 4.2.16 on 2026-04-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_driver_has_pension_driver_has_study_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='google_maps_link',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='waze_link',
        ),
        migrations.AddField(
            model_name='stop',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, help_text='זמן הגעה בפועל (נרשם אוטומטית)', null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='expected_arrival',
            field=models.TimeField(blank=True, help_text='זמן הגעה מתוכנן', null=True),
        ),
        migrations.CreateModel(
            name='StopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='delivery_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.stop')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
