# Generated by Django 4.2.16 on 2026-04-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_stop_google_maps_link_remove_stop_waze_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceFixRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date driver wants corrected')),
                ('requested_clock_in', models.DateTimeField(blank=True, null=True)),
                ('requested_clock_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Why the correction is needed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('manager_note', models.TextField(blank=True, help_text='Manager reply/note')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_fix_requests', to='core.manager')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_requests', to='core.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
