# Generated by Django 4.2.16 on 2026-04-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_attendancefixrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo_b64',
            field=models.TextField(blank=True, default='', help_text='Temporary base64 upload — desktop downloads and clears this'),
        ),
        migrations.AddField(
            model_name='stop',
            name='allow_driver_reorder',
            field=models.BooleanField(default=True, help_text='If True, driver can reorder this stop. Set False for time-locked stops.'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, help_text='Permanent profile photo served via media URL', null=True, upload_to='profile/'),
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_by_name', models.CharField(help_text='Name of person who signed', max_length=200)),
                ('signed_by_phone', models.CharField(blank=True, help_text='Phone to send WhatsApp confirmation to', max_length=30)),
                ('signed_by_email', models.EmailField(blank=True, help_text='Email to send confirmation to', max_length=254)),
                ('signature_image', models.ImageField(help_text='PNG of the hand-drawn signature', upload_to='signatures/%Y/%m/')),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF confirmation', upload_to='confirmations/%Y/%m/')),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='core.stop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
