# Generated by Django 4.2.16 on 2026-05-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_driver_photo_b64_stop_allow_driver_reorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='IAIsJ7bWYIiFA1uvep3yrclcKY0dybGa', max_length=32, unique=True)),
                ('label', models.CharField(blank=True, help_text="e.g. 'משלוח לאתר נתניה'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='core.manager')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='core.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
