# Generated by Django 4.2.16 on 2026-05-11 15:00

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_trackinglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='driver_notified',
            field=models.BooleanField(default=False, help_text='True once driver has been pushed the optimized route'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='route_optimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='route_optimized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='route_suggestion',
            field=models.JSONField(blank=True, help_text='Mapbox suggested stop order + durations + geometry', null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stop',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='stop',
            name='driver_note',
            field=models.TextField(blank=True, help_text='הערת נהג בסיום'),
        ),
        migrations.AddField(
            model_name='stop',
            name='items',
            field=models.TextField(blank=True, help_text='פריטים — חבילה #123, רכב 12-345-67, חומרים לאתר...'),
        ),
        migrations.AddField(
            model_name='stop',
            name='pickup_stop',
            field=models.ForeignKey(blank=True, help_text='עצירת האיסוף שממנה נלקחו הפריטים', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops', to='core.stop'),
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_type',
            field=models.CharField(choices=[('delivery', 'מסירה'), ('pickup', 'איסוף'), ('service', 'שירות'), ('both', 'איסוף + מסירה')], default='delivery', help_text='סוג העצירה', max_length=10),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='target_stop',
            field=models.ForeignKey(blank=True, help_text='Optional — pin tracking page to a specific stop (ETA, client notes target).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_links', to='core.stop'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='token',
            field=models.CharField(default=core.models._new_tracking_token, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='StopTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manager', 'Manager'), ('client', 'Client')], default='manager', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stop_tasks/%Y/%m/')),
                ('phone', models.CharField(blank=True, help_text='Contact phone for driver', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.stop')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
