# Generated by Django 4.2.16 on 2026-05-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dailyschedule_driver_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='auto_closed',
            field=models.BooleanField(db_index=True, default=False, help_text='True if system auto-closed this shift (driver forgot to clock out)'),
        ),
    ]
