# Generated by Django 4.2.16 on 2026-05-16 21:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_attendance_auto_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='deliveryconfirmation',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF confirmation', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='confirmation_pdfs/'),
        ),
        migrations.AlterField(
            model_name='deliveryconfirmation',
            name='signature_image',
            field=models.ImageField(help_text='PNG of the hand-drawn signature', upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, help_text='Permanent profile photo served via media URL', null=True, upload_to='driver_photos/'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('stop_skipped', 'Stop Skipped'), ('day_summary', 'End of Day Summary'), ('clock_reminder', 'Clock Out Reminder'), ('payslip_ready', 'Payslip Ready'), ('license_expiry', 'License Expiry Warning'), ('truck_service', 'Truck Service Due'), ('schedule_changed', 'Schedule Changed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='payslips/'),
        ),
        migrations.AlterField(
            model_name='stopphoto',
            name='image',
            field=models.ImageField(upload_to='delivery_photos/'),
        ),
        migrations.AlterField(
            model_name='stoptask',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stop_task_photos/'),
        ),
    ]
