# Generated by Django 4.2.16 on 2026-05-18 18:04

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_companysettings_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='delivery_note_pdf',
            field=models.FileField(blank=True, help_text='פתק משלוח לחתימה ע״י הלקוח', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='delivery_notes/'),
        ),
    ]
