# Generated by Django 4.2.16 on 2026-05-31 16:59

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_stop_delivery_note_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryconfirmation',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF confirmation', max_length=500, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='confirmation_pdfs/'),
        ),
        migrations.AlterField(
            model_name='deliveryconfirmation',
            name='signature_image',
            field=models.ImageField(help_text='PNG of the hand-drawn signature', max_length=500, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, help_text='Permanent profile photo served via media URL', max_length=500, null=True, upload_to='driver_photos/'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='delivery_note_pdf',
            field=models.FileField(blank=True, help_text='פתק משלוח לחתימה ע״י הלקוח', max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='delivery_notes/'),
        ),
        migrations.AlterField(
            model_name='stopphoto',
            name='image',
            field=models.ImageField(max_length=500, upload_to='delivery_photos/'),
        ),
        migrations.AlterField(
            model_name='stoptask',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='stop_task_photos/'),
        ),
    ]
