# Generated by Django 4.2.16 on 2026-06-06 14:47

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_deliveryconfirmation_pdf_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(blank=True, help_text='ח.פ / עוסק מורשה', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. שוטף+30', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('green_invoice_id', models.CharField(blank=True, help_text='Client id on Green Invoice', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('proforma', 'חשבון עסקה'), ('tax_invoice', 'חשבונית מס'), ('receipt', 'קבלה')], default='proforma', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('number', models.PositiveIntegerField(blank=True, help_text='Internal sequence for proformas; mirrors the provider number for tax docs', null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_tax_id', models.CharField(blank=True, max_length=20)),
                ('client_address', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('vat_exempt', models.BooleanField(default=False)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider', models.CharField(default='truckforce', help_text="'truckforce' for proformas, 'greeninvoice' for legal docs", max_length=20)),
                ('provider_doc_id', models.CharField(blank=True, max_length=64)),
                ('allocation_number', models.CharField(blank=True, help_text='מספר הקצאה', max_length=30)),
                ('pdf_file', models.FileField(blank=True, max_length=500, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='invoices/')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='companysettings',
            name='green_invoice_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='green_invoice_api_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoicing_enabled',
            field=models.BooleanField(default=False, help_text='Billing module on/off per client'),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Before VAT', max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.invoice')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='core.stop')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'הכנסה'), ('expense', 'הוצאה')], max_length=8)),
                ('doc_date', models.DateField(help_text='Drives the year/month archive structure')),
                ('vendor_name', models.CharField(blank=True, help_text='Issuer (for expenses) or payer (for income)', max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional — typed, not calculated', max_digits=12, null=True)),
                ('file', models.FileField(max_length=500, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='finance_docs/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_documents', to='core.client')),
            ],
            options={
                'ordering': ['-doc_date', '-created_at'],
                'indexes': [models.Index(fields=['kind', 'doc_date'], name='core_financ_kind_2c78cb_idx')],
            },
        ),
    ]
