# Generated by Django 4.2.16 on 2026-06-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_client_invoice_companysettings_green_invoice_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='green_invoice_api_key',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='green_invoice_api_secret',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='scan_token',
            field=models.CharField(blank=True, help_text='Upload-only token for the mobile scan page (QR)', max_length=64),
        ),
    ]
