# Generated by Django 4.2.16 on 2026-06-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_companysettings_green_invoice_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='company_tax_id',
            field=models.CharField(blank=True, help_text='ח.פ / עוסק מורשה of the company — printed on invoices', max_length=20),
        ),
        migrations.AddField(
            model_name='financedocument',
            name='vendor_tax_id',
            field=models.CharField(blank=True, help_text='ח.פ / ת.ז on the document', max_length=20),
        ),
    ]
