# Generated by Django 4.2.16 on 2026-06-11 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='can_self_manage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='created_by_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='core.manager'),
        ),
    ]
