# Generated by Django 4.2.16 on 2026-06-12 21:02

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_driver_can_self_manage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Receiver email — delivery note / invoice can be emailed here', max_length=254),
        ),
        migrations.AddField(
            model_name='stop',
            name='invoice_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='stop',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stop',
            name='invoice_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_type',
            field=models.CharField(choices=[('delivery', 'מסירה'), ('pickup', 'איסוף'), ('service', 'שירות'), ('both', 'איסוף + מסירה'), ('package_delivery', 'מסירת חבילות')], default='delivery', help_text='סוג העצירה', max_length=20),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_code', models.CharField(blank=True, max_length=60)),
                ('tmsh_number', models.CharField(blank=True, max_length=60)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('quantity_pallets', models.PositiveIntegerField(default=0)),
                ('quantity_units', models.PositiveIntegerField(default=0)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('checker_name', models.CharField(blank=True, max_length=100)),
                ('returns', models.CharField(blank=True, max_length=200)),
                ('is_loaded', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('loaded', 'נטען'), ('delivered', 'נמסר'), ('returned', 'הוחזר'), ('left', 'נשאר במחסן')], default='pending', max_length=12)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.stop')),
            ],
            options={
                'ordering': ['stop__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_pdf', models.FileField(blank=True, help_text='Blank manifest — photo→PDF or office upload', max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='delivery_sheets/')),
                ('signed_pdf', models.FileField(blank=True, help_text='Running copy — replaced after each signature', max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='delivery_sheets/')),
                ('signature_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sheet', to='core.dailyschedule')),
            ],
        ),
    ]
