# Generated by Django 4.2.16 on 2026-06-13 16:00

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_stop_contact_email_stop_invoice_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What this document is, e.g. "תעודת משלוח"', max_length=200)),
                ('signer_name', models.CharField(blank=True, help_text='Name of the person who signs', max_length=200)),
                ('file', models.FileField(blank=True, help_text='The document file (PDF or image of the paper)', max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='stop_documents/')),
                ('signature_image', models.ImageField(blank=True, help_text='PNG of the hand-drawn signature, once signed', max_length=500, null=True, upload_to='stop_doc_signatures/')),
                ('signed_at', models.DateTimeField(blank=True, help_text='Set when signed; empty = unsigned', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.stop')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
