# Generated by Django 4.2.16 on 2026-08-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_stopdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.CharField(blank=True, db_index=True, help_text='מספר חבילה — the number the office refers to it by', max_length=60)),
                ('code', models.CharField(blank=True, db_index=True, help_text='מק״ט / product code', max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('unit', models.CharField(choices=[('pallet', 'משטח'), ('unit', 'יחידה'), ('box', 'קרטון'), ('bag', 'שק'), ('ton', 'טון'), ('m3', 'מ״ק')], default='pallet', max_length=10)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Standing instructions — gate code, which entrance, call ahead'),
        ),
        migrations.AddField(
            model_name='client',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Google Places id, when picked from the search box', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='location_url',
            field=models.TextField(blank=True, help_text='Google Maps / Waze share link, parsed into coordinates'),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='site_address',
            field=models.TextField(blank=True, help_text='Where the truck goes, when that is not the billing address'),
        ),
        migrations.AddField(
            model_name='client',
            name='site_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='site_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='site_name',
            field=models.CharField(blank=True, help_text='Label shown on the route. Blank → the client name', max_length=200),
        ),
        migrations.AddField(
            model_name='stop',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Saved client this stop was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='core.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, help_text='Billing address — printed on invoices'),
        ),
        migrations.CreateModel(
            name='PackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_date', models.DateField(db_index=True, help_text='The day this is to be delivered')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('scheduled', 'משובץ'), ('delivered', 'נמסר'), ('undelivered', 'לא נמסר'), ('cancelled', 'בוטל')], db_index=True, default='pending', max_length=12)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('original_date', models.DateField(blank=True, help_text='The first date asked for, kept across moves', null=True)),
                ('reschedule_count', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_orders', to='core.client')),
                ('package', models.ForeignKey(help_text='PROTECT: a catalogue row with history is deactivated, never deleted out from under it', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.catalogpackage')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_orders', to='core.stop')),
            ],
            options={
                'ordering': ['delivery_date', 'client__name', 'package__name'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogpackage',
            index=models.Index(fields=['code', 'package_number'], name='core_catalo_code_765542_idx'),
        ),
        migrations.AddIndex(
            model_name='packageorder',
            index=models.Index(fields=['client', 'delivery_date'], name='core_packag_client__10749b_idx'),
        ),
        migrations.AddIndex(
            model_name='packageorder',
            index=models.Index(fields=['status', 'delivery_date'], name='core_packag_status_14ae3e_idx'),
        ),
    ]
